set(_CATKIN_CURRENT_PACKAGE "first_version")
set(first_version_VERSION "0.0.0")
set(first_version_MAINTAINER "smaunrizvi <smaunrizvi@todo.todo>")
set(first_version_PACKAGE_FORMAT "2")
set(first_version_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(first_version_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(first_version_BUILDTOOL_DEPENDS "catkin")
set(first_version_BUILDTOOL_EXPORT_DEPENDS )
set(first_version_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(first_version_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(first_version_TEST_DEPENDS )
set(first_version_DOC_DEPENDS )
set(first_version_URL_WEBSITE "")
set(first_version_URL_BUGTRACKER "")
set(first_version_URL_REPOSITORY "")
set(first_version_DEPRECATED "")