<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- <gazebo> -->
    <!--<plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">

        <legacyMode>false</legacyMode>
        <alwaysOn>true</alwaysOn>
        <updateRate>20</updateRate>

        <leftJoint>left_front_wheel_joint</leftJoint>
        <leftJoint>left_rear_wheel_joint</leftJoint>
        <rightJoint>right_front_wheel_joint</rightJoint>
        <rightJoint>right_rear_wheel_joint</rightJoint>



        <wheelSeparation>${chassis_length/2-wheel_radius}</wheelSeparation>
        <wheelDiameter>0.150</wheelDiameter>

        <rosDebugLevel>INFO</rosDebugLevel>
        <max_wheel_torque>200</max_wheel_torque>
        <max_wheel_acceleration>2</max_wheel_acceleration>
        <wheelAcceleration>0</wheelAcceleration>
        <wheelTorque>50</wheelTorque>
        <odometrySource>world</odometrySource>
        <publishTf>1</publishTf>


        <commandTopic>cmd_vel</commandTopic>
        <odometryTopic>odom</odometryTopic>
        <odometryFrame>odom</odometryFrame>
        <robotBaseFrame>base_link</robotBaseFrame>

        <publishOdom>true</publishOdom>
        <publishOdomTF>true</publishOdomTF>
        <publishWheelTF>true</publishWheelTF>
        <publishWheelJointState>true</publishWheelJointState>

    </plugin>-->
<!-- </gazebo> -->

<gazebo>
    
    <plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
      <legacyMode>false</legacyMode>
      <alwaysOn>true</alwaysOn>
      <updateRate>20</updateRate>

      <!-- <robotNamespace>/robot</robotNamespace> -->
      <leftFrontJoint>left_front_wheel_joint</leftFrontJoint>
      <rightFrontJoint>right_front_wheel_joint</rightFrontJoint>
      <leftRearJoint>left_rear_wheel_joint</leftRearJoint>
      <rightRearJoint>right_rear_wheel_joint</rightRearJoint>  
      
      <wheelSeparation>${chassis_length/2-wheel_radius}</wheelSeparation>
      <wheelDiameter>0.150</wheelDiameter>
      <torque>5</torque>
      <wheelAcceleration>0</wheelAcceleration>
      <!-- <wheelTorque>50</wheelTorque> -->

      <rosDebugLevel>INFO</rosDebugLevel>
  
      
      

      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <robotBaseFrame>base_link</robotBaseFrame>
      <broadcastTF>true</broadcastTF>
      <publishOdom>true</publishOdom>
      <!-- <publishOdomTF>true</publishOdomTF>
      <publishWheelTF>true</publishWheelTF>
      <publishWheelJointState>true</publishWheelJointState> -->
      <odometrySource>world</odometrySource>
      <odometryFrame>odom</odometryFrame>

      <covariance_x>0.0001</covariance_x>
      <covariance_y>0.0001</covariance_y>
      <covariance_yaw>0.01</covariance_yaw>

    </plugin>

  </gazebo>

</robot>